//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Columbia2CertTitle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CertTitleEntities : DbContext
    {
        public CertTitleEntities()
            : base("name=CertTitleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExamEntry> ExamEntries { get; set; }
        public DbSet<IssueEntry> IssueEntries { get; set; }
        public DbSet<SiteUser> SiteUsers { get; set; }
    }
}
