//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Columbia2CertTitle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamEntry
    {
        public ExamEntry()
        {
            this.IssueEntries = new HashSet<IssueEntry>();
        }
    
        public int ID { get; set; }
        public string ExamID { get; set; }
        public string Version { get; set; }
        public string Title { get; set; }
        public string Language { get; set; }
        public string PjM { get; set; }
        public string CDM { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> PlanFinishDate { get; set; }
        public Nullable<System.DateTime> ActualFinishDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IssueCount { get; set; }
        public Nullable<int> IssueCountToEDP { get; set; }
    
        public virtual ICollection<IssueEntry> IssueEntries { get; set; }
    }
}
